---
title: "Molecular Docking Analysis"
subtitle: "BIO512 Structural Biology - Protein-Ligand Docking with YASARA"
author: "Sayyed Jalil Mahdizadeh"
date: November 10, 2025
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
---

# Introduction

The goal of this practical is to understand how molecular glue stabilizes protein-protein interactions. We will work with FKBP12 – a small cytosolic immunophilin and the FRB domain of mTOR. Rapamycin acts as the bridge that "glues" them together, forming a stable FKBP12/rapamycin/FRB ternary complex. When this complex forms, mTOR signaling is reduced, cells decrease anabolic programs (e.g., protein synthesis and growth), slow or arrest the cell cycle, and often increase autophagy.

In this practical, we will perform molecular docking to dock the molecular glue in the interface of two proteins and then we will compare the docking result with the co-crystallized pose.

::: {.callout-important}
## Create a new working directory
```bash
# Create a new folder for this practical
mkdir -p /cephyr/NOBACKUP/groups/n2bin-gu/students/<y/n>/BIO512/MD

```

Open a new desktop session on Vera via OnDemand, then do the following:

1. Open your symlinked folder to the BIO512 group directory (i.e. /cephyr/NOBACKUP/groups/n2bin-gu/) using the file manager
2. Find the directory with the install_yasara executable (in ./BIO512/jalil) and make a copy of the folder to your home directory and execute it (you might need to wait a moment)
3. Once YASARA is open, go Options > Working directory > navigate and find your ‘MD’ folder > OK to set your working directory

We also recommend using jupyter lab for the notebook submission, since base64 encoding of images is a simple drag and drop operation in jupyter lab. To launch jupyter lab, please do the following (locally ofc):

```bash
# Launch the BIO512_v1 env 
conda activate BIO512_v1

# Launch jupyter lab
jupyter lab 
```
:::

::: {.callout-note}
## Learning Objectives
By the end you should be able to:

- Prepare protein structures for molecular docking using YASARA
- Perform protein-ligand docking simulations
- Analyze docking results and binding energies

:::

---

# Structure Preparation

## Setting up the structure

**Download the structure**:

   - File > Load > PDB file from Internet > 3FAP

In the right-hand panel, you can see 3FAP. Click on it to expand it. There are five molecules under 3FAP:

- **Mol A** = chain A of the protein
- **Mol B** = chain B of the protein  
- **Mol A** = ligand (rapamycin)
- **Mol A (in red)** = water molecules of chain A
- **Mol B (in red)** = water molecules of chain B

## Structure cleaning and preparation

**Remove water molecules**:

   - From the right-hand panel, right-click on both water entries and click 'Delete'

**Add missing hydrogen atoms**:

   - Edit > Clean > All

**Minimize the energy of the system**:

   - Options > Choose Experiment > Energy minimization
   
::: {.callout-tip}
## Troubleshooting
On Linux, you may need to pause the minimization if it hangs:
Options > Control experiment > Pause/Continue
:::

**Delete SimCell**:

   - From the right-hand panel, right-click on SimCell and Delete

**Save the prepared complex**:

   - File > Save as > PDB file > select 3FAP from both Sequence and Name panels > give a name (3FAP_complex.pdb)

---

# Receptor and Ligand Separation

## Splitting the complex and saving the individual components

**Split receptor and ligand**:

   - From the right-side panel, right click on 3FAP > split > Split at selected molecules > select the ligand (second A in the sequence panel)
   - Now you can see two objects in the right-hand panel: receptor and ligand

::: {.callout-tip}
## Visualization tip
You can change the color of the receptor and ligand by right-clicking on them in the right-hand panel. It should make it much easier to see the ligand.
:::

**Rename the objects**:

   - Right click on the receptor object > Name > enter "Receptor"
   - Right click on the ligand object > Name > enter "Ligand"

**Save the receptor**:

    - File > Save as > PDB file > select Receptor > OK > give a name (3FAP_receptor.pdb)

**Save the ligand**:

    - File > Save as > Other file format > select Ligand from the Object panel > find sdf-MDL Mol from the Format panel > enter a name (3FAP_ligand) > OK

At this point, you should have three files in your working directory:

- 3FAP_complex.pdb
- 3FAP_receptor.pdb
- 3FAP_ligand.sdf

---

# Docking Simulation Setup

## Defining the simulation cell

**Generate the simulation cell**:

    - From the right-hand panel, right-click on Ligand object > Select > newly
    - Then Simulation > Define simulation cell > around selected atoms

**Remove the ligand**:

    - Right-click on the Ligand object > Delete

**Save the receptor + simulation cell**:

    - File > Save as > YASARA Scene > give a name (3FAP_receptor.sce)

## Running the docking simulation

**Set up docking**:

    - Options > Macro & Movie > set target > select 3FAP_receptor.sce > select 'from underscore' > OK

**Run docking**:

    - Options > Macro & Movie > Play macro > find and click on dock_run.mcr > OK

::: {.callout-note}
## Finding the dock_run.mcr macro
The dock_run.mcr macro is located in the BIO512/jalil folder that you copied, it should be found immediately when you open the macro selection window.
:::

---

# Results Analysis

## Binding energy analysis

**Analyze the results**:

    - Check for the log file (3FAP.log) in the working directory
    - Look at the binding energy values in the first table (Bind.energy)
    - The first entry always has the best binding energy value

::: {.callout-important}
## Q1 What is the binding energy of the best docking pose?
:::

## Visual inspection of docking poses

**Open predicted and crystal structures**:

    - Open the best predicted binding pose (3FAP_001.yob) by YASARA (drag and drop)
    - Open the crystal structure of the ligand (3FAP_ligand.sdf) (drag and drop)

**Optimize visualization**:

    - View > Hide atoms > Aliphatic hydrogens
    - View > Style atoms > Stick > ALL
    - View > Hide atoms > Molecule > A (first entry in the Sequence panel)
    - View > Hide atoms > Molecule > A (second entry in the Sequence panel)

::: {.callout-important}
## Q2 Visually inspect how well the crystal pose and the predicted docking pose overlapped. Do you see a big difference? (1 sentence)
:::

## Quantitative assessment

**Calculate RMSD from crystal pose**:

    - Color the molecules to detect the crystal ligand and docked ligand more easily
    - Analyze > RMSD of > Molecules > docked ligand > OK > crystal ligand > OK > select Molecule > OK
    - The RMSD value will be displayed in the panel below the screen

::: {.callout-important}
## Q3 What is the RMSD between your predicted pose and the crystal structure? Is this considered a successful prediction?
:::

::: {.callout-note}
## Success Criteria
Usually, RMSD < 2.0 Å is considered as a successful docking simulation.
:::

---

# How to Submit Your Work

- Submit answers to the questions in a jupyter notebook (question and answer in the same cell)
- Include screenshots of relevant structures and analyses (you can use the snipping tool or any screenshot tool, then drag and drop the image into the jupyter notebook cell) 